// <copyright file="ConcurrentListTests.Add.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void Add676()
{
    this.Add(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void Add680()
{
    this.Add(1);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void Add695()
{
    this.Add(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void Add113()
{
    this.Add(3);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void Add909()
{
    this.Add(7);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void Add318()
{
    this.Add(15);
}
  }
}
