// <copyright file="ConcurrentListTests.AddParallelSane.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelSane676()
{
    this.AddParallelSane(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelSane680()
{
    this.AddParallelSane(1);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelSane695()
{
    this.AddParallelSane(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelSane113()
{
    this.AddParallelSane(3);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelSane909()
{
    this.AddParallelSane(7);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelSane318()
{
    this.AddParallelSane(15);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
[Ignore("the test state was: path bounds exceeded")]
public void AddParallelSane622()
{
    this.AddParallelSane(63);
}
  }
}
