// <copyright file="ConcurrentListHandWrittenTests.IndexOf.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf985()
{
    int[] ints = new int[0];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf880()
{
    int[] ints = new int[1];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf7101()
{
    int[] ints = new int[2];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf43101()
{
    int[] ints = new int[9];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf48001()
{
    int[] ints = new int[2];
    ints[0] = 1;
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf60001()
{
    int[] ints = new int[10];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf74001()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf4001()
{
    int[] ints = new int[2];
    this.IndexOf(1, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf15401()
{
    int[] ints = new int[14];
    this.IndexOf(1, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf82501()
{
    int[] ints = new int[3];
    this.IndexOf(0, ints);
}
  }
}
