// <copyright file="ConcurrentListHandWrittenTests.GetItem.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void GetItem14901()
{
    this.GetItem(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void GetItem51701()
{
    this.GetItem(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void GetItem44001()
{
    this.GetItem(15);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void GetItem72001()
{
    this.GetItem(1);
}
  }
}
