// <copyright file="ConcurrentListTests.IndexOf.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf985()
{
    int[] ints = new int[0];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf880()
{
    int[] ints = new int[1];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf740()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf71()
{
    int[] ints = new int[2];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf480()
{
    int[] ints = new int[2];
    ints[0] = 1;
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf40()
{
    int[] ints = new int[2];
    this.IndexOf(1, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf825()
{
    int[] ints = new int[3];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf431()
{
    int[] ints = new int[9];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf600()
{
    int[] ints = new int[10];
    this.IndexOf(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void IndexOf536()
{
    int[] ints = new int[40];
    this.IndexOf(1, ints);
}
  }
}
