// <copyright file="ConcurrentListHandWrittenTests.CopyTo.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void CopyTo67601()
{
    this.CopyTo(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void CopyTo68001()
{
    this.CopyTo(1);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void CopyTo69501()
{
    this.CopyTo(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void CopyTo11301()
{
    this.CopyTo(3);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void CopyTo31801()
{
    this.CopyTo(15);
}
  }
}
