// <copyright file="ConcurrentListPexTests.GetEnumerator.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using System.Collections.Generic;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using ConcurrentList;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListPexTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListPexTests))]
public void GetEnumerator29()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      ConcurrentList<int> concurrentList;
      IEnumerator<int> iEnumerator;
      concurrentList = new ConcurrentList<int>();
      iEnumerator = this.GetEnumerator<int>(concurrentList);
      disposables.Add((IDisposable)iEnumerator);
      disposables.Dispose();
      PexAssert.IsNotNull((object)iEnumerator);
      PexAssert.IsNotNull((object)concurrentList);
      PexAssert.AreEqual<int>(0, concurrentList.Count);
    }
}
  }
}
