// <copyright file="ConcurrentListHandWrittenTests.AddParallelCrazy.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Add59301()
{
    this.Add(6);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Add67601()
{
    this.Add(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Add68001()
{
    this.Add(1);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Add69501()
{
    this.Add(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Add113()
{
    this.Add(3);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Add318()
{
    this.Add(15);
}
  }
}
