// <copyright file="ConcurrentListHandWrittenTests.Contains.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains985()
{
    int[] ints = new int[0];
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains880()
{
    int[] ints = new int[1];
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains825()
{
    int[] ints = new int[3];
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains7101()
{
    int[] ints = new int[2];
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains43101()
{
    int[] ints = new int[9];
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains48001()
{
    int[] ints = new int[2];
    ints[0] = 1;
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains74001()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains4001()
{
    int[] ints = new int[2];
    this.Contains(1, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains13801()
{
    int[] ints = new int[9];
    this.Contains(1, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains60001()
{
    int[] ints = new int[10];
    this.Contains(0, ints);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void Contains78701()
{
    int[] ints = new int[42];
    this.Contains(1, ints);
}
  }
}
