// <copyright file="ConcurrentListTests.AddParallelCrazy.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListHandWrittenTests
  {
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelCrazy676()
{
    this.AddParallelCrazy(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelCrazy680()
{
    this.AddParallelCrazy(1);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelCrazy695()
{
    this.AddParallelCrazy(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelCrazy113()
{
    this.AddParallelCrazy(3);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelCrazy909()
{
    this.AddParallelCrazy(7);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListHandWrittenTests))]
public void AddParallelCrazy318()
{
    this.AddParallelCrazy(15);
}
  }
}
