// <copyright file="ConcurrentListTests.CopyTo.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace ConcurrentList.UnitTests
{
  public partial class ConcurrentListTests
  {

[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void CopyTo676()
{
    this.CopyTo(0);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void CopyTo680()
{
    this.CopyTo(1);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void CopyTo695()
{
    this.CopyTo(2);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void CopyTo113()
{
    this.CopyTo(3);
}
[Test]
[PexGeneratedBy(typeof(ConcurrentListTests))]
public void CopyTo318()
{
    this.CopyTo(15);
}
  }
}
